version: "3.8"
services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/mochi
    ports:
      - "3000:1323"
    tty: true
    stdin_open: true
  db:
    container_name: db
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: mochi
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql/
    
volumes:
  db-data: